package com.ghosttorrent;

import generated.*;

/*********************************/
/*   Auto generated by Builder   */
/*********************************/
public class R {

    public Colors color = new Colors();
    public Strings string = new Strings();
    public Images image = new Images();
    public Menus menu = new Menus();
    public Layouts layout = new Layouts();
    public Ids id = new Ids();
}
